# Generated by Django 4.2.16 on 2024-12-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flex_catalog', '0002_dynamiccatalog'),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdysseyCustomCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_catalog.flexiblecatalogmodel')),
                ('filtered_course_runs', models.ManyToManyField(blank=True, limit_choices_to={'org': 'AcademyX'}, related_name='filtered_catalogs', to='course_overviews.courseoverview')),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_catalog.flexiblecatalogmodel',),
        ),
    ]
