# Generated by Django 4.2.16 on 2024-11-29 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleCatalogModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Nombre amigable para humanos.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_catalog.flexiblecatalogmodel')),
                ('course_runs', models.ManyToManyField(blank=True, to='course_overviews.courseoverview')),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_catalog.flexiblecatalogmodel',),
        ),
    ]
