# Generated by Django 4.2.16 on 2024-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex_catalog', '0002_dynamiccatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblecatalogmodel',
            name='name',
            field=models.CharField(help_text='Human friendly', max_length=255),
        ),
    ]
